;;; merlin-eldoc-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from merlin-eldoc.el

(autoload 'merlin-eldoc-setup "merlin-eldoc" "\
Setup eldoc for OCaml/Reasonml based on merlin." t)
(autoload 'merlin-eldoc-disable "merlin-eldoc" "\
Cleanup hooks created by merlin-eldoc." t)
(autoload 'merlin-eldoc-customize "merlin-eldoc" "\
Open the customize buffer for the group merlin-eldoc." t)
(register-definition-prefixes "merlin-eldoc" '("merlin-eldoc-"))

;;; End of scraped data

(provide 'merlin-eldoc-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; merlin-eldoc-autoloads.el ends here
