;;; yascroll-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from yascroll.el

(autoload 'yascroll:show-scroll-bar "yascroll" "\
Default key to show all scroll bars." t)
(autoload 'yascroll:hide-scroll-bar "yascroll" "\
Hide scroll bar of BUFFER." t)
(autoload 'yascroll-bar-mode "yascroll" "\
Yet Another Scroll Bar Mode.

This is a minor mode.  If called interactively, toggle the
`Yascroll-Bar mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `yascroll-bar-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(put 'global-yascroll-bar-mode 'globalized-minor-mode t)
(defvar global-yascroll-bar-mode nil "\
Non-nil if Global Yascroll-Bar mode is enabled.
See the `global-yascroll-bar-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-yascroll-bar-mode'.")
(custom-autoload 'global-yascroll-bar-mode "yascroll" nil)
(autoload 'global-yascroll-bar-mode "yascroll" "\
Toggle Yascroll-Bar mode in all buffers.
With prefix ARG, enable Global Yascroll-Bar mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Yascroll-Bar mode is enabled in all buffers where `yascroll:turn-on'
would do it.

See `yascroll-bar-mode' for more information on Yascroll-Bar mode.

(fn &optional ARG)" t)
(register-definition-prefixes "yascroll" '("yascroll:"))

;;; End of scraped data

(provide 'yascroll-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; yascroll-autoloads.el ends here
