;;; Automatically generated by ‘recentf’ on Mon Jan  6 16:28:37 2025.

(setq recentf-list
      '(
        "~/.dotfiles/openbox/.config/openbox/autostart"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
